language: ruby
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
rvm:
  - 2.2
install:
  - gem install jekyll
  - gem install html-proofer
script:
  - jekyll build
#  - htmlproof _site --only-4xx
